services:
  cleanarchitecture.db:
    image: postgres:16
    
  cleanarchitecture.api:
    image: ${DOCKER_REGISTRY-}cleanarchitectureapi
    build:
      context: .
      dockerfile: src/CleanArchitecture/CleanArchitecture.Api/Dockerfile
  
  serilogseq:
    image: datalust/seq:2023.4
    
volumes:
  pg_db:
  seq_data:  