services:
  cleanarchitecture.db:
    container_name: cleanarchitecture.db
    environment:
      POSTGRES_DB: cleanarchitecturedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_db:/var/lib/postgresql/data
    
  cleanarchitecture.api:
    environment:
      
      - ConnectionStrings__Database=Server=cleanarchitecture.db;Port=5432;Database=cleanarchitecturedb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - cleanarchitecture.db
    ports:
      - "5000:8080" #puerto contenedor : puerto interno app
      # - "5001:8081"  comentado porque no estoy utiliazando https
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  serilogseq:
    container_name: serilogseq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80" #puerto para la interfaz grafica
    volumes:
      - seq_data:/data  